name: Semantic Release
on:
    push:
        branches: [main]

jobs:
    release:
        name: Release version
        runs-on: ubuntu-latest
        environment: Semantic Release
        steps:
            - name: Decode the GitHub App Private Key
              id: decode
              run: |
                private_key=$(echo "${{ secrets.G_RELEASES_APP_PRIVATE_KEY_BASE64 }}" | base64 -d | awk 'BEGIN {ORS="\\n"} {print}' | head -c -2) &> /dev/null
                echo "::add-mask::$private_key"
                echo "private-key=$private_key" >> "$GITHUB_OUTPUT"
            - name: Generate GitHub App Token
              id: github-app-token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ vars.G_RELEASES_APP_ID }}
                  private-key: ${{ steps.decode.outputs.private-key }}
            - name: Semantic Release
              uses: icedrone/semantic-release-actions@v1
              env:
                  github_token: ${{ steps.github-app-token.outputs.token }}