name: Semantic Release
on:
    push:
        branches: [main]

jobs:
    release:
        name: Release version
        runs-on: ubuntu-latest
        environment: Semantic Release
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - name: Generate GitHub App Token
              id: github-app-token
              run: |
                  node .github/scripts/generate-token.cjs
              env:
                  GITHUB_APP_ID: ${{ vars.G_RELEASES_APP_ID }}
                  GITHUB_APP_PRIVATE_KEY_BASE64: ${{ secrets.GITHUB_APP_PRIVATE_KEY_BASE64 }}
                  GITHUB_APP_INSTALLATION_ID: ${{ vars.G_RELEASES_APP_INSTALLATION_ID }}

            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}